openapi: "3.0.2"
info:
  title: Linked Connections API
  description: This API presents all the stops and vehicle departures (ordered by departure time)  from the Belgian public transport networks, namely SNCB, De Lijn, MIVB and TEC, following the [Linked Connections](https://linkedconnections.org/) data model and the [Linked Data principles](https://www.w3.org/DesignIssues/LinkedData.html).
  version: 1.0.0
  contact:
    name: Pieter Colpaert
    url: https://pietercolpaert.be/
    email: pieter.colpaert@ugent.be
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: https://creativecommons.org/licenses/by-sa/4.0/
externalDocs:
  description: Linked Connections documentation for developers
  url: https://linkedconnections.org/specification/1-0
tags:
- name: connections
  description: Vehicle (train, bus or tram) departures from one stop to another, at certain points in time 
- name: stops
  description: List of stops where passengers can enter/exit the vehicles
paths:
  /sncb/connections:
    servers:
    - url: https://graph.irail.be/
    get:
      tags: 
      - connections
      summary: List of SNCB Linked Connections 
      description: Returns a list of _Linked Connections_ ordered by departure time. **This operation applies only for SNCB**
      parameters: 
      - name: departureTime
        in: query
        description: Reference date for the returned vehicle departures. If not given, the reference date will be assumed as the _current_ date determiend at the reception of the HTTP request on the server.
        schema:
          type: string
          format: date-time
          example: "2019-09-01T09:00:00.000Z"
      - name: Accept-Datetime
        in: header
        description: Time-based content negotiation header for accessig historic data using the [Memento protocol](https://tools.ietf.org/html/rfc7089). The API will return the _Linked Connections_ as they were published on the provided (or closest available) date.
        schema:
          type: string
          format: date-time
          example: "2019-06-01T09:00:00.000Z"
          externalDocs:
            description: Memento IETF specification
            url: https://tools.ietf.org/html/rfc7089
      responses:
        200:
          description: List of _Linked Connections_ for a certain time window.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/linkedConnections'
        404:
          description: No _Linked Connections_ available for the requested date
  /mivb/connections:
    servers:
    - url: https://openplanner.ilabt.imec.be/
    get:
      tags: 
      - connections
      summary: List of MIVB Linked Connections 
      description: Returns a list of _Linked Connections_ ordered by departure time. **This operation applies only for MIVB**
      parameters: 
      - name: departureTime
        in: query
        description: Reference date for the returned vehicle departures. If not given, the reference date will be assumed as the _current_ date determiend at the reception of the HTTP request on the server.
        schema:
          type: string
          format: date-time
          example: "2019-09-01T09:00:00.000Z"
      - name: Accept-Datetime
        in: header
        description: Time-based content negotiation header for accessig historic data using the [Memento protocol](https://tools.ietf.org/html/rfc7089). The API will return the _Linked Connections_ as they were published on the provided (or closest available) date.
        schema:
          type: string
          format: date-time
          example: "2019-06-01T09:00:00.000Z"
          externalDocs:
            description: Memento IETF specification
            url: https://tools.ietf.org/html/rfc7089
      responses:
        200:
          description: List of _Linked Connections_ for a certain time window.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/linkedConnections'
        404:
          description: No _Linked Connections_ available for the requested date
  /tec/connections:
    servers:
    - url: https://openplanner.ilabt.imec.be/
    get:
      tags: 
      - connections
      summary: List of TEC Linked Connections 
      description: Returns a list of _Linked Connections_ ordered by departure time. **This operation applies only for TEC**
      parameters: 
      - name: departureTime
        in: query
        description: Reference date for the returned vehicle departures. If not given, the reference date will be assumed as the _current_ date determiend at the reception of the HTTP request on the server.
        schema:
          type: string
          format: date-time
          example: "2019-09-01T09:00:00.000Z"
      - name: Accept-Datetime
        in: header
        description: Time-based content negotiation header for accessig historic data using the [Memento protocol](https://tools.ietf.org/html/rfc7089). The API will return the _Linked Connections_ as they were published on the provided (or closest available) date.
        schema:
          type: string
          format: date-time
          example: "2019-06-01T09:00:00.000Z"
          externalDocs:
            description: Memento IETF specification
            url: https://tools.ietf.org/html/rfc7089
      responses:
        200:
          description: List of _Linked Connections_ for a certain time window.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/linkedConnections'
        404:
          description: No _Linked Connections_ available for the requested date
  /delijn/{region}/connections:
    servers:
    - url: https://openplanner.ilabt.imec.be/
    get:
      tags:
      -  connections
      summary: List of De Lijn Linked Connections 
      description: Returns a list of _Linked Connections_ ordered by departure time. **This operation applies only for De Lijn**
      parameters: 
      - name: region
        in: path
        description: Name of the administrative region
        required: true
        schema:
          type: string
          enum: 
          - Antwerpen
          - Limburg
          - Oost-Vlaanderen
          - Vlaams-Brabant
          - West-Vlaanderen
      - name: departureTime
        in: query
        description: Reference date for the returned vehicle departures. If not given, the reference date will be assumed as the _current_ date determiend at the reception of the HTTP request on the server.
        schema:
          type: string
          format: date-time
          example: "2019-09-01T09:00:00.000Z"
      - name: Accept-Datetime
        in: header
        description: Time-based content negotiation header for accessig historic data using the [Memento protocol](https://tools.ietf.org/html/rfc7089). The API will return the _Linked Connections_ as they were published on the provided (or closest available) date.
        schema:
          type: string
          format: date-time
          example: "2019-06-01T09:00:00.000Z"
          externalDocs:
            description: Memento IETF specification
            url: https://tools.ietf.org/html/rfc7089
      responses:
        200:
          description: List of _Linked Connections_ for a certain time window.
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/linkedConnections'
        404:
          description: No _Linked Connections_ available for the requested date
  /sncb/stops:
    servers:
    - url: https://graph.irail.be/
    get:
      tags:
      - stops
      summary: List of stops of the SNCB public tranpsort network in Belgium
      description: Returns a list of stops
      responses:
        200:
          description: List of stops
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/stops'
        404:
          description: Uknown administrative region
  /mivb/stops:
    servers:
    - url: https://openplanner.ilabt.imec.be/
    get:
      tags:
      - stops
      summary: List of stops of the MIVB public tranpsort network in Brussels
      description: Returns a list of stops
      responses:
        200:
          description: List of stops
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/stops'
        404:
          description: Uknown administrative region
  /tec/stops:
    servers:
    - url: https://openplanner.ilabt.imec.be/
    get:
      tags:
      - stops
      summary: List of stops of the TEC public tranpsort network in Wallonia
      description: Returns a list of stops
      responses:
        200:
          description: List of stops
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/stops'
        404:
          description: Uknown administrative region
  /delijn/{region}/stops:
    servers:
    - url: https://openplanner.ilabt.imec.be/
    get:
      tags:
      - stops
      summary: List of stops of De Lijn for a certain region in Flanders
      description: Returns a list of stops
      parameters: 
      - name: region
        in: path
        description: Name of the administrative region
        required: true
        schema:
          type: string
          enum: 
          - Antwerpen
          - Limburg
          - Oost-Vlaanderen
          - Vlaams-Brabant
          - West-Vlaanderen
      responses:
        200:
          description: List of stops
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/stops'
        404:
          description: Uknown administrative region
components:
  schemas:
    stop:
      description: Stop data structure
      type: object
      properties:
        "@id":
          type: string
          format: uri
          description: Unique identifier of the stop
          example: "https://data.delijn.be/stops/200001"
        country:
          type: string
          format: uri
          description: GeoNames URI of the country where the stop is located
          example: "http://sws.geonames.org/2802361"
        latitude:
          type: number
          format: float
          description: Geographical latitude of the stop
          example: 51.1105
        longitude:
          type: number
          format: float
          description: Geographical longitude of the stop
          example: 3.6994
        name:
          type: string
          description: Name of the stop
          example: Brielken
        operationZone:
          type: string
          format: uri
          description: Administrative region the stop belongs to
          example: "https://data.delijn.be/entiteit/Oost-Vlaanderen"
    linkedConnection:
      description: _Linked Connection_ data structure
      type: object
      properties:
        "@id":
          type: string
          format: uri
          description: Unique identifier of the _Linked Connection_
          example: "http://irail.be/connections/8891140/20190906/IC1532"
        "@type": 
          type: string
          description: Indicates if the connection is/was scheduled to happen or not
          enum:
          - Connection
          - CancelledConnection
        departureStop:
          type: string
          format: uri
          description: Stop from which the vehicle is departing
          example: "http://irail.be/stations/NMBS/008891140"
        departureTime:
          type: string
          format: date-time
          description: Date and time of the vehicle departure
          example: "2019-09-06T09:38:00.000Z"
        arrivalStop:
          type: string
          format: uri
          description: Stop the vehicle is travelling to
          example: "http://irail.be/stations/NMBS/008891132"
        arrivalTime:
          type: string
          format: date-time
          description: Date and time of the vehicle arrival
          example: "2019-09-06T09:41:00.000Z"
        "gtfs:trip":
          type: string
          format: uri
          description: Unique identifier of the vehicle trip
          example: "http://irail.be/vehicle/IC1532/20190906"
        "gtfs:route":
          type: string
          format: uri
          description: Unique identifier of the vehicle route
          example: "http://irail.be/vehicle/IC1532"
        direction: 
          type: string
          description: Label of the vehicle destination. Normally displayed on the vehicle's screens
          example: Blankenberge
        "gtfs:pickupType":
          type: string
          description: Describes if passangers are allowed and how to board the vehicle at the departure stop
          enum: 
          - "gtfs:Regular"
          - "gtfs:NotAvailable"
          - "gtfs:MustPhone"
          - "gtfs:MustCoordinateWithDriver"
        "gtfs:dropOffType":
          type: string
          description: Describes if passangers are allowed and how to exit the vehicle at the arrival stop
          enum: 
          - "gtfs:Regular"
          - "gtfs:NotAvailable"
          - "gtfs:MustPhone"
          - "gtfs:MustCoordinateWithDriver"
        departureDelay:
          type: number
          format: int32
          description: The amount of reported delay in seconds (when available) that a vehicle has for departing a certain stop
          example: 300
        arrivalDelay:
          type: number
          format: int32
          description: The amount of reported delay in seconds (when available) that a vehicle has for arriving at a certain stop
          example: 300
      externalDocs:
        description: See the GTFS specification for more details
        url: "https://developers.google.com/transit/gtfs/"
    stops:
      type: object
      description: Web document that contains a set of stops
      properties:
        "@graph":
           type: array
           description: List of stops
           items:
             $ref: '#/components/schemas/stop'
    linkedConnections:
      type: object
      description: Web document that contains a set of _Linked Connections_
      properties:
        "@id":
          type: string
          format: uri
          description: Unique identifier for a set of _Linked Connections_
          example: "https://graph.irail.be/sncb/connections?departureTime=2019-09-06T09:38:00.000Z"
        "hydra:next":
          type: string
          format: url
          description: The next list of chronologically ordered _Linked Connections_
          example: "https://graph.irail.be/sncb/connections?departureTime=2019-09-06T09:57:00.000Z"
        "hydra:previous":
          type: string
          format: url
          description: The previous list of chronologically ordered _Linked Connections_
          example: "https://graph.irail.be/sncb/connections?departureTime=2019-09-06T09:20:00.000Z"
        "@graph":
          type: array
          description: The list of _Linked Connections_
          items:
            $ref: '#/components/schemas/linkedConnection'